export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const UPDATE_CART_QTY = 'UPDATE_CART_QTY';
export const INCREMENT_CART_QTY = 'INCREMENT_CART_QTY';
export const DECREMENT_CART_QTY = 'DECREMENT_CART_QTY';
